name: GFM
favicon: null
layout_spectrum: 0.6486382966395468
typography_spectrum: 0.6759393853135407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5198728682007641
  lightness: 0.7171312419231981
  saturation: 0.02954908669926226
  rhythmicContrast: 0.0029314709827303886
purpose: []
